- name: Setup SystemD Catalogue Service copy the file to SystemD
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service
    # change to copy means [copy as it from there]
    # but now it will go template folder then go to catalogue.service change tocatalogue.service.j2
    # from there it  

- name: Load the service.systemctl deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable service
  ansible.builtin.service:
    name: catalogue
    state: restarted # even app is not ruuning restart 
    enabled: yes 
